#******************************************************
# Joseph Winters
# Dictionary holding verbs with irregular conjugations
# Fall 2016
#******************************************************


import conjugation as conj
import helper_verbs as hv
import verb
import tense as tn


IRREGULAR_VERBS = {
    "acheter":
        verb.Verb("acheter",
                  futur_simple_stem="achèter",
                  present_conjugation=conj.Conjugation("acheter",
                                                       tn.Tense.PRESENT,
                                                       "achète", "achètes",
                                                       "achète", "achetons",
                                                       "achetez", "achètent")),
    "aller":
        verb.Verb("aller",
                  futur_simple_stem="ir",
                  present_conjugation=hv.ALLER_PRESENT),
    "appeler":
        verb.Verb("appeler",
                  futur_simple_stem="appeller",
                  present_conjugation=conj.Conjugation("appeler",
                                                       tn.Tense.PRESENT,
                                                       "appelle", "appelles",
                                                       "appelle", "appelons",
                                                       "appelez",
                                                       "appellent")),
    "apprendre":
        verb.Verb("apprendre",
                  participe_passe="appris",
                  present_conjugation=conj.Conjugation("apprendre",
                                                       tn.Tense.PRESENT,
                                                       "apprends", "apprends",
                                                       "apprend", "apprenons",
                                                       "apprenez",
                                                       "apprennent")),
    "avoir":
        verb.Verb("avoir",
                  participe_passe="eu",
                  futur_simple_stem="aur",
                  present_conjugation=hv.AVOIR_PRESENT),
    "comprendre":
        verb.Verb("comprendre",
                  participe_passe="compris",
                  present_conjugation=conj.Conjugation("comprendre",
                                                       tn.Tense.PRESENT,
                                                       "comprends",
                                                       "comprends",
                                                       "comprend",
                                                       "comprenons",
                                                       "comprenez",
                                                       "comprennent")),
    "connaître":
        verb.Verb("connaître",
                  participe_passe="connu",
                  present_conjugation=conj.Conjugation("connaître",
                                                       tn.Tense.PRESENT,
                                                       "connais", "connais",
                                                       "connaît",
                                                       "connaissons",
                                                       "connaissez",
                                                       "connaissent")),
    "courir":
        verb.Verb("courir",
                  participe_passe="couru",
                  futur_simple_stem="courr",
                  present_conjugation=conj.Conjugation("courir",
                                                       tn.Tense.PRESENT,
                                                       "cours", "cours",
                                                       "court", "courons",
                                                       "courez", "courent")),
    "couvrir":
        verb.Verb("couvrir",
                  participe_passe="couvert",
                  present_conjugation=conj.Conjugation("couvrir",
                                                       tn.Tense.PRESENT,
                                                       "couvre", "couvres",
                                                       "couvre", "couvrons",
                                                       "couvrez", "couvrent")),
    "croire":
        verb.Verb("croire",
                  participe_passe="cru",
                  present_conjugation=conj.Conjugation("croire",
                                                       tn.Tense.PRESENT,
                                                       "crois", "crois",
                                                       "croit", "croyons",
                                                       "croyez", "croient")),
    "découvrir":
        verb.Verb("découvrir",
                  participe_passe="découvert",
                  present_conjugation=conj.Conjugation("découvrir",
                                                       tn.Tense.PRESENT,
                                                       "découvre", "découvres",
                                                       "découvre",
                                                       "découvrons",
                                                       "découvrez",
                                                       "découvrent")),
    "devenir":
        verb.Verb("devenir",
                  participe_passe="devenu",
                  futur_simple_stem="deviendr",
                  present_conjugation=conj.Conjugation("devenir",
                                                       tn.Tense.PRESENT,
                                                       "deviens", "deviens",
                                                       "devient", "devenons",
                                                       "deveniez",
                                                       "deviennent")),
    "devoir":
        verb.Verb("devoir",
                  participe_passe="dû",
                  futur_simple_stem="devr",
                  present_conjugation=conj.Conjugation("devoir",
                                                       tn.Tense.PRESENT,
                                                       "dois", "dois", "doit",
                                                       "devons", "devez",
                                                       "doivent")),
    "dormir":
        verb.Verb("dormir",
                  present_conjugation=conj.Conjugation("dormir",
                                                       tn.Tense.PRESENT,
                                                       "dors", "dors", "dort",
                                                       "dormons", "dormez",
                                                       "dorment")),
    "endormir":
        verb.Verb("endormir",
                  present_conjugation=conj.Conjugation("endormir",
                                                       tn.Tense.PRESENT,
                                                       "endors", "endors",
                                                       "endort", "endormons",
                                                       "endormez",
                                                       "endorment")),
    "envoyer":
        verb.Verb("envoyer",
                  participe_passe="envoyé",
                  futur_simple_stem="enverr",
                  present_conjugation=conj.Conjugation("envoyer",
                                                       tn.Tense.PRESENT,
                                                       "envoie", "envoies",
                                                       "envoie", "envoyons",
                                                       "envoyez", "envoient")),
    "être":
        verb.Verb("être",
                  participe_passe="été",
                  imparfait_stem="ét",
                  futur_simple_stem="ser",
                  present_conjugation=hv.ETRE_PRESENT),
    "faire":
        verb.Verb("faire",
                  participe_passe="fait",
                  futur_simple_stem="fer",
                  present_conjugation=conj.Conjugation("faire",
                                                       tn.Tense.PRESENT,
                                                       "fais", "fais", "fait",
                                                       "faisons", "faites",
                                                       "font")),
    "mentir":
        verb.Verb("mentir",
                  present_conjugation=conj.Conjugation("mentir",
                                                       tn.Tense.PRESENT,
                                                       "mens", "mens", "ment",
                                                       "mentons", "mentez",
                                                       "mentent")),
    "mentir":
        verb.Verb("mentir",
                  present_conjugation=conj.Conjugation("mentir",
                                                       tn.Tense.PRESENT,
                                                       "mens", "mens", "ment",
                                                       "mentons", "mentez",
                                                       "mentent")),
    "mettre":
        verb.Verb("mettre",
                  participe_passe="mis",
                  present_conjugation=conj.Conjugation("mettre",
                                                       tn.Tense.PRESENT,
                                                       "mets", "mets", "met",
                                                       "mettons", "mettez",
                                                       "mettent")),
    "mourir":
        verb.Verb("mourir",
                  participe_passe="mort",
                  futur_simple_stem="mourr",
                  present_conjugation=conj.Conjugation("mourir",
                                                       tn.Tense.PRESENT,
                                                       "meurs", "meurs",
                                                       "meurt", "mourons",
                                                       "mourez", "meurent")),
    "naître":
        verb.Verb("naître",
                  participe_passe="né",
                  present_conjugation=conj.Conjugation("naître",
                                                       tn.Tense.PRESENT,
                                                       "nais", "nais", "naît",
                                                       "naissons", "naissez",
                                                       "naissent")),
    "offrir":
        verb.Verb("offrir",
                  participe_passe="offert",
                  present_conjugation=conj.Conjugation("offrir",
                                                       tn.Tense.PRESENT,
                                                       "offre", "offres",
                                                       "offre", "offrons",
                                                       "offrez", "offrent")),
    "partir":
        verb.Verb("partir",
                  present_conjugation=conj.Conjugation("partir",
                                                       tn.Tense.PRESENT,
                                                       "pars", "pars", "part",
                                                       "partons", "partez",
                                                       "partent")),
    "pouvoir":
        verb.Verb("pouvoir",
                  participe_passe="pu",
                  futur_simple_stem="pourr",
                  present_conjugation=conj.Conjugation("pouvoir",
                                                       tn.Tense.PRESENT,
                                                       "peux", "peux", "peut",
                                                       "pouvons", "pouvez",
                                                       "peuvent")),
    "préférer":
        verb.Verb("préférer",
                  present_conjugation=conj.Conjugation("préférer",
                                                       tn.Tense.PRESENT,
                                                       "préfère", "préfères",
                                                       "préfère", "préférons",
                                                       "préférez",
                                                       "préfèrent")),
    "prendre":
        verb.Verb("prendre",
                  participe_passe="pris",
                  present_conjugation=conj.Conjugation("prendre",
                                                       tn.Tense.PRESENT,
                                                       "prends", "prends",
                                                       "prend", "prenons",
                                                       "prenez", "prennent")),
    "recevoir":
        verb.Verb("recevoir",
                  participe_passe="reçu",
                  futur_simple_stem="recevr",
                  present_conjugation=conj.Conjugation("recevoir",
                                                       tn.Tense.PRESENT,
                                                       "reçois", "reçois",
                                                       "reçoit", "recevons",
                                                       "recevez",
                                                       "reçoivent")),
    "revenir":
        verb.Verb("revenir",
                  participe_passe="revenu",
                  futur_simple_stem="reviendr",
                  present_conjugation=conj.Conjugation("revenir",
                                                       tn.Tense.PRESENT,
                                                       "reviens", "reviens",
                                                       "revient", "revenons",
                                                       "reveniez",
                                                       "reviennent")),
    "savoir":
        verb.Verb("savoir",
                  participe_passe="su",
                  futur_simple_stem="saur",
                  present_conjugation=conj.Conjugation("savoir",
                                                       tn.Tense.PRESENT,
                                                       "sais", "sais", "sait",
                                                       "savons", "savez",
                                                       "savent")),
    "sentir":
        verb.Verb("sentir",
                  present_conjugation=conj.Conjugation("sentir",
                                                       tn.Tense.PRESENT,
                                                       "sens", "sens", "sent",
                                                       "sentons", "sentez",
                                                       "sentent")),
    "servir":
        verb.Verb("servir",
                  present_conjugation=conj.Conjugation("servir",
                                                       tn.Tense.PRESENT,
                                                       "sers", "sers", "sert",
                                                       "servons", "servez",
                                                       "servent")),
    "sortir":
        verb.Verb("sortir",
                  present_conjugation=conj.Conjugation("sortir",
                                                       tn.Tense.PRESENT,
                                                       "sors", "sors", "sort",
                                                       "sortons", "sortez",
                                                       "sortent")),
    "souffrir":
        verb.Verb("souffrir",
                  participe_passe="souffert",
                  present_conjugation=conj.Conjugation("souffrir",
                                                       tn.Tense.PRESENT,
                                                       "souffre", "souffres",
                                                       "souffre", "souffrons",
                                                       "souffrez",
                                                       "souffrent")),
    "venir":
        verb.Verb("venir",
                  participe_passe="venu",
                  futur_simple_stem="viendr",
                  present_conjugation=conj.Conjugation("venir",
                                                       tn.Tense.PRESENT,
                                                       "viens", "viens",
                                                       "vient", "venons",
                                                       "venez", "viennent")),
    "vivre":
        verb.Verb("vivre",
                  participe_passe="vécu",
                  present_conjugation=conj.Conjugation("vivre",
                                                       tn.Tense.PRESENT,
                                                       "vis", "vis", "vit",
                                                       "vivons", "vivez",
                                                       "vivent")),
    "voir":
        verb.Verb("voir",
                  participe_passe="vu",
                  futur_simple_stem="verr",
                  present_conjugation=conj.Conjugation("voir",
                                                       tn.Tense.PRESENT,
                                                       "vois", "vois", "voit",
                                                       "voyons", "voyez",
                                                       "voient")),
    "vouloir":
        verb.Verb("vouloir",
                  participe_passe="voulu",
                  imparfait_stem="voul",
                  futur_simple_stem="voudr",
                  present_conjugation=conj.Conjugation("vouloir",
                                                       tn.Tense.PRESENT,
                                                       "veux", "veux", "veut",
                                                       "voulons", "voulez",
                                                       "veulent"))
}
